version: 2.1
executors:
  android-executor:
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      GRADLE_USER_HOME: /tmp/workspace/.gradle
jobs:
  test:
    executor: android-executor
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "gradle.properties" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - /tmp/workspace/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}-{{ checksum  "gradle.properties" }}
      - run:
          name: Disable Pre-Dexing
          command: cp .circleci/init.gradle $GRADLE_USER_HOME/init.gradle
      - run:
          name: Lint & Test
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - persist_to_workspace:
          root: /tmp/workspace/
          paths:
            - .gradle
  build_debug:
    executor: android-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace/
      - checkout
      - run:
          name: Build debug apk
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/apk/debug/app-debug.apk
          destination: debug-apk
      - persist_to_workspace:
          root: /tmp/workspace/
          paths:
            - .gradle
  build_release:
    executor: android-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace/
      - checkout
      - run:
          name: Signing Setup
          command: .circleci/signing_setup.sh
      - run:
          name: Build release apk
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: release-apk
      - persist_to_workspace:
          root: /tmp/workspace/
          paths:
            - .gradle
  deploy:
    executor: android-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace/
      - checkout
      - run:
          name: Signing Setup
          command: .circleci/signing_setup.sh
      - run:
          name: Deploy
          command: ./gradlew publish

workflows:
  version: 2.1
  test_build_deploy:
    jobs:
      - test
      - build_debug:
          requires:
            - test
      - build_release:
          requires:
            - test
          filters:
            branches:
              only:
                - dev
                - master
      - deploy:
          requires:
            - build_debug
            - build_release
          filters:
            branches:
              only:
                - master
